### ISSUE TITLE
@AutoInjector into multiple components

### ISSUE THREAD

**Issue by vpratfr** [lukaspili/Auto-Dagger2#4]
Hi,

Is there any reason why we cannot auto-inject a class from multiple components? Would that be some clue of bad design or would that be something which could be useful?

**Comment by lukaspili** [comment]
Yes you can, `@AutoInjector` can take an array of values: 
`@AutoInjector({Activity1.class, Activity2.class})`

**Comment by vpratfr** [comment]
Cool. Thanks.
