### ISSUE TITLE
@AutoSubcomponent annotation

### ISSUE THREAD

**Issue by ersin-ertan** [lukaspili/Auto-Dagger2#5]
I tried to extend the object graph to the subcomponent from a component, I have the component extend via the `superinterface = SubComponentWorkAroundSuperinterface.class` to get the method in the generated AppComponent

``` java
@AppScope(App.class) @AutoComponent(modules = App.AppModule.class, superinterfaces = SubComponentsWorkAround.class)
public class App extends Application{...}

@AppScope(App.class)  @Component(modules = User.UserModule.class)
public interface SubComponentsWorkAroundSuperinterface{
    ObjectType plus(ObjectModule objectModule);
}
```
## 

but get the error "Members injection methods may only return the injected type or void."

Would an `@UserScope @AutoSubcomponent(modules = User.UserModule.class) class User{...}` solve this, allowing us to use the plus(), perhaps in conjunction with another new annotation that is a combination of the the two `@AutoExpose + @AutoInjector = @AutoPlus`?

**Comment by nbonavia** [comment]
To contributors,

I was trying to investigate on adopting auto dagger in my project but unfortunately had to abandon due to lack of support to SubComponent creation. Is it something that is in your roadmap to implement?

Implementing nested components requires the implementation of methods that provide instantiation of the sub-component at the top level component e.g.: -

AuthenticationComponent authenticationComponent(AuthenticationModule authenticationModule);

GameComponent gameComponent(GameModule gameModule);

Thanks
Neville.

**Comment by lukaspili** [comment]
@nbonavia @ersin-ertan 
Hey guys, sorry for the slow reaction on this.
I just added support for subcomponents with a new annotation `@AutoSubcomponent`.

It works in the same way as `@AutoComponent`. 
The attribute `addsTo` defines to which component the current subcomponent will be added to:

``` java

// Will generate MySubObjectComponent class which be itself annotated with @Subcomponent

@AutoSubcomponent(addsTo = MyApp.class)
@DaggerScope(MySubObject1.class)
public class MySubObject1 {

}
```

I published the 1.2-SNAPSHOT version with the subcomponent support.
You need to add the snapshot repository: 

``` groovy
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

Let me know if that solves your case, and if all is good I'll release the 1.2 version to maven central.
Thanks!

**Comment by ersin-ertan** [comment]
Hey Lukas, thanks for the update and the new annotation. Unfortunately I will not be able to verify this for ~1 month. If @nbonavia or someone else could step up and try it out with feedback that would be great, for version 1.2, and closing the issue.

**Comment by nbonavia** [comment]
hi @ersin-ertan  and @lukaspili ,

I am planning to verify this very shortly, typically this week or maybe the next one. I will be sending you feedback shortly.

Thanks for your response
@nbonavia

**Comment by lukaspili** [comment]
That's cool :) Thanks

**Comment by nbonavia** [comment]
Quick Question @lukaspili , how can I inform the Component which are its sub-components so that it'll automatically create interfaces to create the Dagger Sub-Component instances?. Typical Component to sub-component interface links are as shown below: -

AuthenticationComponent authenticationComponent(AuthenticationModule authenticationModule);

GameComponent gameComponent(GameModule gameModule);

Can these be auto-generated using autodagger?

Neville.

**Comment by lukaspili** [comment]
@nbonavia I realized I wrote the implementation following the inverse logic, starting from @AutoSubcomponent, which was wrong.

I just pushed a new 1.2-SNAPSHOT version with new API changes:

Step 1. Generate the subcomponent if you need, or you can use manually created Subcomponent.

``` java
// Will generate MySubObjectComponent class which be annotated with @Subcomponent
@AutoSubcomponent
@DaggerScope(MySubObject1.class)
public class MySubObject1 {

}
```

Step 2. Add the subcomponent to the @AutoComponent

``` java
// Will generate FirstActivityComponent with a subcomponent for MySubObject1
@AutoComponent(
        subcomponents = MySubObject1.class
)
@DaggerScope(FirstActivity.class)
public class FirstActivity extends Activity {

}
```

**Comment by lennynilsson** [comment]
Hi @lukaspili,

Nice work with the library. I'm working with @nbonavia and was thinking I would try your project out.
Is the 1.2-SNAPSHOT available on Github?

**Comment by lukaspili** [comment]
It's available as maven jar in the sonatype snapshot repository.
You need to add the repository in your gradle config first, and then you can use the dependency as usual.

``` groovy
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    apt 'com.github.lukaspili.autodagger2:autodagger2-compiler:1.2-SNAPSHOT'
    compile 'com.github.lukaspili.autodagger2:autodagger2:1.2-SNAPSHOT'
}
```

**Comment by yaneq6** [comment]
Hey dude, this is awesome work but i see lack of two functionalities about autosubcomponents. 

Firstly, it's not possible to use module with non empty default constructor. Autodagger generates plus-method for specified subcomponent but without module as parameter.

Secondly, autosubcomponent annotation does not provide option to specify subcomponents on itself. It's impossible to do something like this: `@AutoSubcomponent(subcomponents = arrayOf(Subcomponent2::class))`

I'm sure that I will use auto-dagger2 in the future if these two issues will be solved. Best regards from Poland
